services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-todo-api:local
    container_name: golang-todo-api
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DATABASE_URL=/data/app.db
    ports:
      - '8080:8080'
    volumes:
      - ./data:/data
    restart: unless-stopped
